name: 'SemVer Tagger'
description: 'Genera tags SemVer automáticamente con control de canales'
author: 'Midnattsol'

inputs:
  bump:
    description: 'Nivel de versionado: major, minor, patch'
    required: true
    default: 'patch'
  channel:
    description: 'Canal de release: release-candidate, release'
    required: true
    default: 'release'
  dry-run:
    description: 'Simula el proceso sin crear tags realmente'
    required: false
    default: false
    type: boolean
  github-token:
    description: 'Token de GitHub para autenticación'
    required: true

outputs:
  new_tag:
    description: 'El nuevo tag generado'
    value: ${{ steps.tagger.outputs.new_tag }}

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub semver
      working-directory: ${{ github.action_path }}

    - name: Run SemVer Tagger
      id: tagger
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        python ${{ github.action_path }}/main.py \
          --bump "${{ inputs.bump }}" \
          --channel "${{ inputs.channel }}" \
          --sha "${{ github.sha }}" \
          --repo "${{ github.repository }}" \
          ${{ inputs.dry-run && '--dry-run' || '' }}
      working-directory: ${{ github.action_path }}