name: 'Release Tagger'
description: 'Genera tags SemVer usando Python'
inputs:
  release-level:
    description: 'Nivel de release: major, minor, patch'
    required: true
    default: 'patch'
  release-channel:
    description: 'Canal: beta, rc, release'
    required: true
    default: 'release'

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      shell: bash
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt
      working-directory: ${{ github.action_path }}

    - name: Run Python Tagger
      shell: bash
      run: |
        python ${{ github.action_path }}/tagger.py \
          --level "${{ inputs.release-level }}" \
          --channel "${{ inputs.release-channel }}" \
          --sha "${{ github.sha }}" \
          --repo "${{ github.repository }}"
      working-directory: ${{ github.action_path }}