name: 'Release Tagger'
description: 'Genera tags SemVer usando Python'
inputs:
  release-level:
    description: 'Nivel de release: major, minor, patch'
    required: true
    default: 'patch'
  release-channel:
    description: 'Canal: beta, rc, release'
    required: true
    default: 'release'
  dry-run: 
    description: Ejecuta el tagging imprimiendo los nuevos tags sin crearlos
    required: false
    default: false
    type: boolean
  token:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      shell: bash
      run: |
        pip install -r ${{ github.action_path }}/requirements.txt
      working-directory: ${{ github.action_path }}

    - name: Run Python Tagger
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}      
      run: |
        echo ${{ inputs.dry-run }}
        DRY_RUN=$([[ ${{ inputs.dry-run }} = 'true' ]] && echo '--dry-run' || echo '')
        python ${{ github.action_path }}/main.py \
          --level "${{ inputs.release-level }}" \
          --channel "${{ inputs.release-channel }}" \
          --sha "${{ github.sha }}" \
          --repo "${{ github.repository }}" \
          $DRY_RUN
      working-directory: ${{ github.action_path }}